paths:
  tasks: tasks
defaultExecutor: claude-code
postApplyCommands:
  - title: Format JS code
    command: pnpm run format
    workingDirectory: web
    allowFailure: true
    hideOutputOnSuccess: true
  - title: Format Rust code
    command: cargo fmt
    workingDirectory: server
    allowFailure: true
    hideOutputOnSuccess: true
executors:
  claude-code:
    permissionsMcp:
      enabled: true
      timeout: 60000
      defaultResponse: no
      autoApproveCreatedFileDeletion: true
prCreation:
  draft: true
